In [18]:
import numpy as np
m = np.array([2,2])
m

array([2, 2])

In [24]:
X = np.array([[1,2], [3,4]])
X

array([[1, 2],
       [3, 4]])

In [29]:
out = np.dot(X,m)
out

array([ 6, 14])

In [35]:
X.T

array([[1, 3],
       [2, 4]])

In [36]:
out2 = X.T.dot(m)
out2

array([ 8, 12])