In [2]:
# coding=utf-8
import numpy as np
import matplotlib.pyplot as plt
import operator
def create_dataset():
    datasets = np.array([[8,4,2],[7,1,1],[1,4,4],[3,0,5]])
    labels = ['非常热','非常热','一般热','一般热']
    return datasets, labels


def analyze_data_plot(x, y):
    plt.rc('font', family='SimHei', size=7)  ##显示中文
    fig = plt.figure()
    #将画布划分为1行1列1块
    ax = fig.add_subplot(111)
    ax.scatter(x, y)
    plt.title('游客冷热感知散点图',fontsize=25)
    plt.xlabel('天热吃冰淇淋数目',fontsize=15)
    plt.ylabel('天热喝水数目',fontsize=15)
    #保存为文件，放在当前目录下
    plt.savefig('datasets_plot.png',bbox_inches='tight')
    plt.show()
    
"""kNN近邻算法模型"""
"""这个算法主要工作是测量不同特征值之间的距离，有个这个距离，就可以进行分类了"""
"""已知：训练集，以及每个训练集的标签。
   接下来：和训练集中的数据对比，计算最相似的k个距离。选择相似数据中最多的那个分类。作为新数据的分类。"""
def knn_Classifier(newV, datasets, label, k):
    #1.计算数据与样本数据的距离
    sqrtDist = EuclideanDistance(newV,datasets)
    #2. 根据距离进行排序,axis=0进行列排序，axis=1进行行排序,返回从小到大排序的值的索引
    sortedDistIndexs=sqrtDist.argsort(axis=0)
    #3. 针对k个点，统计各个类别的数量
    classCount = {}
    for i in range(k):
        voteLabel = labels[sortedDistIndexs[i]]
        #统计类标签的键值对
        classCount[voteLabel] = classCount.get(voteLabel,0)+1
    #4.投票机制 少数服从多数原则            这里key的值代表使用classCount的value值排序，reverse值True是从大到小排序
    sortedClassCount = sorted(classCount.items(),key=operator.itemgetter(1),reverse=True)
    return sortedClassCount[0][0]
    pass

# 欧式距离
def EuclideanDistance(newV, datasets):
    rowsize, colsize = datasets.shape
    #数据与每个数据样本的差
    #扩充成一样的数组，得到目标与训练数值之间的差值
    diffMat = np.tile(newV,(rowsize,1))-datasets
    sqDiffMat = diffMat ** 2  #各个元素分别平方
    # 差值平方和进行开方（axis=1表示每行累加）
    sqrtDist = sqDiffMat.sum(axis=1) ** 0.5
    return sqrtDist
    pass

def predict_temperature():
    #1. 创建数据集和标签
    datasets, labels = create_dataset()
    #2. 获取最新信息
    iceCream = float(input('iceCream ：\n'))
    drinkWater = float(input('drinkWater: \n'))
    playTime =float(input('palyTime: \n'))
    
    newV = np.array([iceCream,drinkWater,playTime])
    res = knn_Classifier(newV, datasets,labels,3)
    print('The weather is: ',res)

if __name__ == '__main__':
    datasets, labels = create_dataset()
    print('数据集:\n',datasets)
    print('标签:\n',labels)
    
    #analyze_data_plot(datasets[:,0],datasets[:,1])
    k = 3
    newV = [2, 4, 4]
    #knn_Classifier(newV, datasets, labels, k)
    vecs = np.array([[2,4,4],[3,0,0],[5,7,2]])
    for vec in vecs:
        res = knn_Classifier(vec,datasets,labels,k)
        print(vec,'kNN预测结果:',res)
    predict_temperature()

数据集:
 [[8 4 2]
 [7 1 1]
 [1 4 4]
 [3 0 5]]
标签:
 ['非常热', '非常热', '一般热', '一般热']
[2 4 4] kNN预测结果: 一般热
[3 0 0] kNN预测结果: 一般热
[5 7 2] kNN预测结果: 非常热
iceCream ：
4
drinkWater: 
2
palyTime: 
2
The weather is:  一般热
