In [1]:
import numpy as np

In [2]:
a = np.array([1,2])

In [3]:
a.dtype

dtype('int32')

In [4]:
a = np.array([1.1,2.2])

In [5]:
a.dtype

dtype('float64')

In [6]:
a = np.array([1,2.2])

In [7]:
a

array([1. , 2.2])

In [8]:
a.dtype

dtype('float64')

In [9]:
a = np.array([1.1,2.6])

In [10]:
a = np.array([1.1,2.6],dtype=np.int64)

In [11]:
a

array([1, 2], dtype=int64)

In [12]:
b =np.array(a,dtype=np.int64)

In [13]:
b

array([1, 2], dtype=int64)

数学运算与常用函数

In [14]:
a = np.array([[1,2],
             [3,4]])

In [15]:
b = np.array([[5,6],
             [6,5]])

In [16]:
a+b

array([[6, 8],
       [9, 9]])

In [17]:
a-b

array([[-4, -4],
       [-3, -1]])

In [18]:
np.add(a,b)

array([[6, 8],
       [9, 9]])

In [19]:
np.subtract(a,b)

array([[-4, -4],
       [-3, -1]])

In [20]:
a*b

array([[ 5, 12],
       [18, 20]])

In [22]:
np.multiply(a,b)

array([[ 5, 12],
       [18, 20]])

In [23]:
a/b

array([[0.2       , 0.33333333],
       [0.5       , 0.8       ]])

In [24]:
np.divide(a,b)

array([[0.2       , 0.33333333],
       [0.5       , 0.8       ]])

In [25]:
np.sqrt(a)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ]])

In [26]:
a

array([[1, 2],
       [3, 4]])

In [27]:
b = np.array([[1,2,3],
             [4,5,6]])

In [28]:
a.dot(b)

array([[ 9, 12, 15],
       [19, 26, 33]])

In [29]:
np.dot(a,b)

array([[ 9, 12, 15],
       [19, 26, 33]])

# 常用函数

sum

In [30]:
a

array([[1, 2],
       [3, 4]])

In [31]:
np.sum(a)

10

In [32]:
np.sum(a,axis=0)

array([4, 6])

In [33]:
np.sum(a,axis=1)

array([3, 7])

mean

In [34]:
np.mean(a)

2.5

In [35]:
np.mean(a,axis=0)

array([2., 3.])

In [36]:
a

array([[1, 2],
       [3, 4]])

In [37]:
np.mean(a,axis=1)

array([1.5, 3.5])

uniform 指定区间随机值

In [40]:
np.random.uniform(3,4)

3.660854527508653

In [41]:
np.random.uniform(1,100)

46.33713796270107

tile数组重复连接

In [42]:
a

array([[1, 2],
       [3, 4]])

In [43]:
np.tile(a,(1,2))

array([[1, 2, 1, 2],
       [3, 4, 3, 4]])

In [44]:
np.tile(a,(2,1))

array([[1, 2],
       [3, 4],
       [1, 2],
       [3, 4]])

argsort

In [45]:
a = np.array([[3,6,4,11],
             [5,10,1,3]])

In [46]:
a.argsort()#每一行index从小到大排列

array([[0, 2, 1, 3],
       [2, 3, 0, 1]], dtype=int64)

In [47]:
a.argsort(axis=0) #每一列从小到大index排列

array([[0, 0, 1, 1],
       [1, 1, 0, 0]], dtype=int64)

矩阵转置

In [48]:
np.transpose(a)

array([[ 3,  5],
       [ 6, 10],
       [ 4,  1],
       [11,  3]])

In [49]:
a

array([[ 3,  6,  4, 11],
       [ 5, 10,  1,  3]])

### 广播

In [63]:
a = np.array([[1,2,3],
             [2,3,4],
             [12,31,22],
             [2,2,2]])

In [64]:
b = np.array([1,2,3])

In [65]:
for i in range(4):
    a[i,:] += b

In [66]:
a

array([[ 2,  4,  6],
       [ 3,  5,  7],
       [13, 33, 25],
       [ 3,  4,  5]])

In [67]:
a+np.tile(b,(4,1))

array([[ 3,  6,  9],
       [ 4,  7, 10],
       [14, 35, 28],
       [ 4,  6,  8]])

In [68]:
a+b  #直接加，即是广播特性，自动补全b的缺失行，然后相加

array([[ 3,  6,  9],
       [ 4,  7, 10],
       [14, 35, 28],
       [ 4,  6,  8]])