In [1]:
import numpy as np

In [2]:
a = np.array([[1,2,3,4],
             [5,6,7,8],
             [9,10,11,12]])

In [3]:
a[-2,1:3]

array([6, 7])

In [4]:
a[-2:,1:3]

array([[ 6,  7],
       [10, 11]])

In [5]:
a[1,-2]

7

In [6]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [7]:
a.shape

(3, 4)

In [8]:
b = a[-2:,1:3]

In [9]:
b.shape

(2, 2)

In [10]:
b

array([[ 6,  7],
       [10, 11]])

In [11]:
b = a[2,1:3]

In [12]:
b

array([10, 11])

In [13]:
b.shape

(2,)

In [14]:
b=a[2:3,1:3]

In [15]:
b

array([[10, 11]])

In [16]:
b.shape

(1, 2)

In [17]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [18]:
a[np.arange(3),1]+=10

In [19]:
a

array([[ 1, 12,  3,  4],
       [ 5, 16,  7,  8],
       [ 9, 20, 11, 12]])

In [20]:
np.arange(3)

array([0, 1, 2])

In [21]:
np.arange(3,7)

array([3, 4, 5, 6])

In [22]:
a[np.arange(3),[1,1,1]]+=10

In [23]:
a

array([[ 1, 22,  3,  4],
       [ 5, 26,  7,  8],
       [ 9, 30, 11, 12]])

In [24]:
a[[0,1,2],[1,1,1]]+=10

In [25]:
a

array([[ 1, 32,  3,  4],
       [ 5, 36,  7,  8],
       [ 9, 40, 11, 12]])

In [26]:
result_index = a>10

In [27]:
result_index

array([[False,  True, False, False],
       [False,  True, False, False],
       [False,  True,  True,  True]])

In [28]:
a[result_index]

array([32, 36, 40, 11, 12])

In [29]:
a[a>10]

array([32, 36, 40, 11, 12])