# Array(数组)

In [6]:
import numpy as np

In [7]:
a = np.array([1,2,3])

In [8]:
a

array([1, 2, 3])

In [9]:
type(a)

numpy.ndarray

In [10]:
a.shape

(3,)

In [11]:
a = a.reshape((1,-1))

In [12]:
a.shape

(1, 3)

In [13]:
a = np.array([1,2,3,4,5,6])

In [14]:
a.shape

(6,)

In [15]:
a = a.reshape((2,-1))

In [17]:
a.shape

(2, 3)

In [18]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [19]:
a = a.reshape((-1,2))

In [20]:
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [21]:
a.shape

(3, 2)

In [22]:
a[2][0] = 55

In [23]:
a

array([[ 1,  2],
       [ 3,  4],
       [55,  6]])

zeros

In [24]:
a = np.zeros((3,3))

In [25]:
a

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

ones

In [26]:
a = np.ones((2,3))

In [27]:
a

array([[1., 1., 1.],
       [1., 1., 1.]])

full

In [28]:
a = np.full((3,3),0)

In [29]:
a

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [30]:
a = np.full((3,3),1)

In [31]:
a

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

eye

In [32]:
a = np.eye(3)

In [33]:
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

random.random

In [34]:
a = np.random.random((3,4))

In [35]:
a

array([[0.79638894, 0.2370219 , 0.68178194, 0.0409316 ],
       [0.34788907, 0.01123803, 0.65673683, 0.25259186],
       [0.5313993 , 0.35267105, 0.24562529, 0.86157624]])