In [1]:
import keras
from keras.datasets import mnist
from keras.models import Sequential
from keras.layers import Dense
from keras.optimizers import SGD

Using TensorFlow backend.


In [2]:
(x_train, y_train), (x_test, y_test) = mnist.load_data()

In [3]:
print(x_train.shape, y_train.shape)
print(x_test.shape, y_test.shape)

(60000, 28, 28) (60000,)
(10000, 28, 28) (10000,)


In [4]:
import matplotlib.pyplot as plt
im = plt.imshow(x_train[0],cmap='gray')
plt.show()

<Figure size 640x480 with 1 Axes>

In [5]:
y_train[0]

5

In [6]:
x_train = x_train.reshape(60000, 784)
x_test = x_test.reshape(10000,784)

In [7]:
print(x_train.shape)

(60000, 784)


### 图片数据点的取值范围是(0,255),需要归一化(0,1)

In [8]:
x_train = x_train/255
x_test = x_test /255

In [9]:
#数据进行one-hot   2 -> [0,0,1,0,0,0,0,0,0,0]
print(y_train)
y_train = keras.utils.to_categorical(y_train,10)
print(y_train)
y_test = keras.utils.to_categorical(y_test,10)

[5 0 4 ... 5 6 8]
[[0. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]]


In [10]:
model = Sequential() #全连接层
#隐含层, 多层感知机
model.add(Dense(512,activation='relu',input_shape=(784,))) #输入层，需要告知输入大小，此处是一维元素长度是784
model.add(Dense(256,activation='relu')) #   relu 克服梯度消失的问题,加快训练速度
model.add(Dense(10,activation='softmax'))  # 输出层，10个输出 数字类型在0-9

Instructions for updating:
Colocations handled automatically by placer.


In [11]:
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              (None, 512)               401920    
_________________________________________________________________
dense_2 (Dense)              (None, 256)               131328    
_________________________________________________________________
dense_3 (Dense)              (None, 10)                2570      
Total params: 535,818
Trainable params: 535,818
Non-trainable params: 0
_________________________________________________________________


In [12]:
# SGD随机梯度下降法
model.compile(optimizer=SGD(), loss = 'categorical_crossentropy',metrics=['accuracy'])

In [13]:
model.fit(x_train,y_train,batch_size=64,epochs=5,validation_data=(x_test,y_test))  #batch_size 一次输入64个样本

Instructions for updating:
Use tf.cast instead.
Train on 60000 samples, validate on 10000 samples
Epoch 1/5
60000/60000 [==============================] - 13s 220us/step - loss: 0.7499 - acc: 0.8254 - val_loss: 0.3657 - val_acc: 0.9021
Epoch 2/5
60000/60000 [==============================] - 11s 186us/step - loss: 0.3346 - acc: 0.9063 - val_loss: 0.2859 - val_acc: 0.9211
Epoch 3/5
60000/60000 [==============================] - 13s 218us/step - loss: 0.2797 - acc: 0.9205 - val_loss: 0.2499 - val_acc: 0.9306
Epoch 4/5
60000/60000 [==============================] - 11s 190us/step - loss: 0.2468 - acc: 0.9306 - val_loss: 0.2267 - val_acc: 0.9365
Epoch 5/5
60000/60000 [==============================] - 12s 199us/step - loss: 0.2222 - acc: 0.9372 - val_loss: 0.2060 - val_acc: 0.9417


In [14]:
score = model.evaluate(x_test,y_test)

10000/10000 [==============================] - 1s 98us/step


In [15]:
print("Loss:",score[0])
print("Accuracy:",score[1])

Loss: 0.20604384335428477
Accuracy: 0.9417
